#!/usr/bin/env bash
# Modify /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo -e "\n8.8.8.8 \tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
